spring:
  application:
    name: service-pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_pay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: dulida
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.lida.cloud.service.impl
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    serialization: kryo
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
    port: 8848
  provider:
    #random随机，roundrobin轮询 ，leastactive最少活跃数，consistenthash哈希
    loadbalance: roundrobin
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lida.cloud.**.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
idWorker:
  dataCenterId: 1
  machineId: 1
