server:
  port: 9000
spring:
  application:
    name: auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: dulida
  main:
    allow-bean-definition-overriding: true
auth:
  clientId: clientId #客户端ID
  clientSecret: clientSecret #客户端密钥
encrypt:
  key-store:
    location: classpath:/changgou.jks #证书路径（公钥加密私钥解密）
    secret: changgou #密钥
    alias: changgou #证书别名
    password: changgou #证书密码