spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: dulida
  application:
    name: service-user
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.lida.cloud.service.impl
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    serialization: kryo
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
    port: 8848
  provider:
    #random随机，roundrobin轮询 ，leastactive最少活跃数，consistenthash哈希
    loadbalance: roundrobin
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lida.cloud.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
idWorker:
  dataCenterId: 1
  machineId: 1
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: world-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
  issuer: world-admin-issuer  #JWT负载中拿到开头